add explicit failure for pipeline

diff --git a/.github/workflows/test-rixpress-python-pipeline.yaml b/.github/workflows/test-rixpress-python-pipeline.yaml
--- a/.github/workflows/test-rixpress-python-pipeline.yaml
+++ b/.github/workflows/test-rixpress-python-pipeline.yaml
@@ -46,3 +46,10 @@ jobs:
       - name: Make pipeline
         run: |
           nix-shell --quiet --run "cd data-raw/py_example && Rscript -e \"devtools::load_all();rixpress::rxp_make()\""
+
+      - name: Check if directory exists
+        run: |
+          if [ ! -d "data-raw/py_example/result" ]; then
+            echo "Error: Directory 'pipeline failed!' does not exist."
+            exit 1
+          fi
diff --git a/.github/workflows/test-rixpress-simple-pipeline.yaml b/.github/workflows/test-rixpress-simple-pipeline.yaml
--- a/.github/workflows/test-rixpress-simple-pipeline.yaml
+++ b/.github/workflows/test-rixpress-simple-pipeline.yaml
@@ -46,3 +46,12 @@ jobs:
       - name: Make pipeline
         run: |
           nix-shell --quiet --run "cd data-raw && Rscript -e \"devtools::load_all();rixpress::rxp_make()\""
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Check if directory exists
+        run: |
+          if [ ! -d "data-raw/result" ]; then
+            echo "Error: Directory 'pipeline failed!' does not exist."
+            exit 1
+          fi
